// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
		}

		public class Variables
		{
		}

		public class Channels
		{
		}
	}
}
